version: '3'
services:

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: "user"
      MINIO_ROOT_PASSWORD: "password"
    command: ["minio", "server", "/data", "--console-address", ":9001"]
    volumes:
      - ./tmp/minio:/data:cached
    ports:
      - "9000:9000"
      - "9001:9001"